### PR TITLE
Tweak current.parindent setting to reset itself automatically

### LINKED ISSUE #188: document.parindent setting not working at the beginning of document
Using sile at HEAD:

```
\begin[papersize=a4]{document}%
\font[family=Kohinoor Devanagari,language=hi]
\set[parameter=document.parindent,value=0pt]
\font[style=Light]
दीपक जोइस

\font[style=Medium]
दीपक जोइस

\font[style=Bold]
दीपक जोइस
\end{document}
```

Produces output:
screenshot 2015-11-10 10 07 01

I was expecting the first paragraph to not be intended as well.

### PR DESCRIPTION
**Pull request by deepakjois**
* Make `current.parindent` nil by default (this fixes #188)
* Reset it to nil once we have indented the current paragraph
* Remove redundant calls to reset `current.parindent` to zero, because now it is reset to nil immediately after a new paragraph is started.

### CODE REVIEW

**Comment by deepakjois** [comment]
Please take a close look at the removal of calls to `current.parindent`. I removed these calls only in the cases that I thought it would be already nil.

**Comment by deepakjois** [comment]
Don’t think the build failure is due to these commits.

**Comment by simoncozens** [comment]
No, that's me messing something else up.

**Comment by simoncozens** [comment]
Thanks very much!

**Pull request merged**
