### PR TITLE
Clean up Travis recipie

### PR DESCRIPTION
**Pull request by alerque**
This is just some odds and eds to clean up the shell scripting involved in the Travis test runs. This should make it easier to maintain and easier to read the debug log and make sense out of what step fails when they do.

### CODE REVIEW

**Comment by simoncozens** [comment]
While you're messing, it might be good - perhaps as another option in the build matrix - to build lua 5.3 with compatibility-grandfathering turned off, (remove `-DLUA_COMPAT_5_2` from the Makefile) so we are prepared for whatever surprises the Lua community decide to spring on us in the next release.

**Comment by alerque** [comment]
@simoncozens Good idea. I've added a test to the matrix for that.

I think I pissed off Travis running so many jobs. I'm stuck behind some queue now but when it does get around to testing this one last time I think I'm about done with this bit of hacking.

**Comment by alerque** [comment]
I lied. I have a couple more tweaks to test when Travis starts minding me again.

**Comment by alerque** [comment]
Alright Travis says green, I say green.

Things I learned today:

1. Debuging shell scripts inside Travis build scripts is way more of a pain than it should be. They are mucking around with every line and it screws up normal shell quoting, variable scoping and basic syntax.
2. Lua has changed the way they do a lot of things and the different versions are pretty different to test. Case in point: the output of `lua -v` is on STDERR for 5.1 and STDOUT for 5.2 and 5.3. At some point it might be necessary to write write different build tests for each version. Meh.

**Comment by simoncozens** [comment]
Lovely, thank you!

**Pull request merged**
