### PR TITLE
Don't try to iterate over and append nil type to table

### PR DESCRIPTION
**Pull request by alerque**
See issue #213.

I don't know if this is actually the correct fix or if this should be checked more intelligently upstream, but it gets me by to do a successful rendering pass.

### CODE REVIEW

**Comment by alerque** [comment]
I just realized that this "fix" was eating my chapter headers and some page breaks. I tweaked it again so that it doesn't destroy my documents, but the same caveat as above still applies.

**Comment by simoncozens** [comment]
Sorry, but I don't like this fix. I think it should actually throw an error with traceback (`SU.error(...,true)`) so we can find out *why* it's being passed nil parameters.

**Comment by alerque** [comment]
I agree this isn't a proper fix, but I don't know enough about what should be passed to this function to debug the upstream part. The PR was more for the sake of seeing test output and being able to show you where the problem was surfacing that because I thought it should be merged.

**Comment by simoncozens** [comment]
Try this instead. If you do get assertion failures, (I don't get any processing your document) then please file them as issues.

**Comment by alerque** [comment]
You don't get any in my document because this hack is in my document. Nuke it from the end of the `avadanlik/viachristus.lua` file and you'll get the error. Depending on your font situation it might vary on what page it bombs.

**Pull request closed without merging**
