### PR TITLE
Seek and destroy 262 (and all its friends)

### LINKED ISSUE #262: Page break resets rskip/lskip. Sometimes.
Since the fix for #255 I have an elusive issue with my block quote environments that have lskip/rskip values applied. Sometimes when a page break happens inside the environment, the next page will not be properly typeset. What's funny is the font settings are coming across, but not the adjusted margins.

Even funnier, it only happens sometimes.

Even funnier, if I tweak the `document.spaceskip` value ever-so-slightly so that the whole document lays out with slightly different line breaks and the words break in a different place, which blocks fail and which succeed changes. I have a couple different styles with different fonts and line spacing inside the environoments and they all fail sometimes and succeed sometimes.

Here's a win:

selection_156

Here's a fail:

selection_155

But wait. Here is that las fail — winning:

selection_157

The only difference between this and the previous compile is this:

``` diff
-\set[parameter=document.spaceskip,value=0.5en plus 0.45en minus 0.2en]
+\set[parameter=document.spaceskip,value=0.55en plus 0.45en minus 0.2en]
```

### PR DESCRIPTION
**Pull request by alerque**
Fixes #262. Maybe — cross your fingers, toes, branches, whatever you've got.

This probably needs work, but  I need to see the test suite relative to a merge rather than just my branch. Also if you'd like me to  rebase the cosmetic stuff into a separate PR from the functional changes I can do that.

### CODE REVIEW

**Comment by alerque** [comment]
Now also fixes #344 which was a closely related.

**Comment by alerque** [comment]
Now also fixes #301. All these things were pretty closely related.

**Comment by alerque** [comment]
This is progress, but I'm not out of the woods yet. There is still something whacky going on in documents that have use in-document page templates or switch masters. Some of those tests worked, but a few broke pretty badly and there is still at least one regression in that we're not discarding something that should be (and had previously been fixed to be). In any event I'm out of time for now.

**Comment by alerque** [comment]
Hey @simoncozens if you have a few  minutes can we jump in [the Gitter room](https://gitter.im/simoncozens/sile)? This is going to be a bug-bear to finish and merge and I'd like to do it as painlessly as possible, but it would be nice to coordinate.

**Comment by alerque** [comment]
This is down to one issue. Somehow or another I've broken the page builder in the test where it switches masters. Interestingly everything typesets correctly and the pushBack() seems to be working there, but two PDF pages are overlaid on top of each other.  Ideas?

**Comment by alerque** [comment]
It only took 999 tries, but Travis is [giving this a green light](https://travis-ci.org/simoncozens/sile/builds/157015418)!

**Comment by simoncozens** [comment]
Excellent! I want to read them all first and make sure I understand them, but green lights make me happy.

**Comment by alerque** [comment]
There are a couple bits of commits that _don't_ make sense, but I left them in for the history. For example my line leading snafu. When I touch functions I usually look up when they were added, how they were changed and where they are used. The were they are currently used is usually a matter of `git grep <function>`, but the when and why I usually look for in `git log -S <function>`. I left my mistake in messing with `inhibitLeading()` because the change and revert commits document why _not_ to change it: `git log -S inhibitLeading` leaves a pretty solid trail of why that is there and why it is not somewhere else.

**Comment by simoncozens** [comment]
All good! Thank you so much for this!

**Pull request merged**
