### PR TITLE
Add support for COLR/CPAL color fonts

### PR DESCRIPTION
**Pull request by khaledhosny**
Very crude and probably inefficient, but seems to work.

I wasn’t sure where to put the get_table() function, harfbuzz module seemed to be the closest.

Issues I’m not sure how to address:
- [x] Cache the parsed tables instead of parsing them for each shaping call.
- [ ] Add an option to `\font` to select which pallette to use.
- [x] Get glyph names of the layers, but are glyph names used at all?

### CODE REVIEW

**Comment by simoncozens** [comment]
I haven't looked at this in detail but is there a way we could also tie this in with the OpenType parsing package? Either make that use get_table or move the colour parsing stuff into there or both?

**Comment by khaledhosny** [comment]
I think moving the parsing part to the OpenType parsing package and making it use `get_table` makes sense, I’ll give it a try.

**Comment by khaledhosny** [comment]
Moved table parsing code code to the OpenType parsing package, this does not handle caching I think, but at least it makes it a geneal issue :)

**Comment by khaledhosny** [comment]
Did a boor caching attempt, seems to save decrease the times the tables are parsed, but does not eliminate all unnecessary ones, probably because the life cycle of the face is short.

**Comment by khaledhosny** [comment]
Taking inspiration (read outright copy paste) from the font fallback package, the color fonts package is now self-contained; no changes needed to node maker.

**Comment by khaledhosny** [comment]
Screenshot from the PDF of the test file, for anyone wondering how it looks like:

**Comment by simoncozens** [comment]
This is fantastic! Thank you!

**Comment by alerque** [comment]
:8ball:

**Comment by behdad** [comment]
At some point in the future I like to add the COLR/CPAL code to HarfBuzz...

**Comment by khaledhosny** [comment]
I’d give it a try, but the API can be tricky, a new buffer flag? and how to return the color to the clients, a new `hb_glyph_info_t` field, would that break the ABI?

**Comment by behdad** [comment]
> I’d give it a try, but the API can be tricky, a new buffer flag? and how to return the color to the clients, a new hb_glyph_info_t field, would that break the ABI?

Yeah, I haven't decided on the API yet.  At the outset, it will be new API to allow querying COLR/CPAL.  The integration with shaping will be trickier.  We can return color in hb_glyph_info_t's var1.  It might be easier to ignore integrating with hb-shape, and have a separate function that takes a shaped buffer and does color substitutions.

**Pull request merged**
