### PR TITLE
 \setLTR and \setRTL support

### PR DESCRIPTION
**Pull request by deepakjois**
This is a first attempt at adding support for bidirectional text across multiple frames (see #77) . It seems to have at least one serious bug. Compare [intended output][1] to [actual output][2]. Notice the header on top of the second page just vanishes unexpectedly. I can’t quite figure out why that is the case.

[1]: https://dl.dropboxusercontent.com/u/953/site_assets/urdu_sile.pdf
[2]: https://dl.dropboxusercontent.com/u/953/urdu_assg.pdf

Some other points for discussion:

* The idea of using `\setLTR` and `\setRTL` for switching the direction of paragraphs is borrowed from TeX’s [bidi][3] package
* Given SILE is intended to be a next-gen typesetting package, bidi support should be built-in to one of the default document classes, probably `plain`. We should not need to import a package to get bidi support.
* There should be support for typesetting short RTL text inside LTR paragraphs as well (and vice versa), something equivalent to the TeX bidi pacakages `\LRE` and `\RLE`

[3]: https://www.ctan.org/pkg/bidi?lang=en

Please let me know what you think of this approach, or if you have any alternative suggestions.

### CODE REVIEW

**Comment by deepakjois** [comment]
Ok. I made another commit, where I try to set the frame direction much earlier than when `newPar` is called. I also moved the methods to the `plain.lua` class.

However, I am getting some weird output again. The x-offset of some nodes seem to be way off. [Here][1] is how the doc looks like now. Compare with expected (linked in previous comment) output and see how the document header disappears, and the header on the second paragraph is not center aligned.

It seems that there might be some problem in the `nodefactory.lua` methods where some `moveX` commands are being issued, based on the frame direction. Could you explain what is going on there. That will help me debug further.

[1]: https://dl.dropboxusercontent.com/u/953/urdu_assg_1.pdf

**Comment by deepakjois** [comment]
I made another commit. This fixes the centering on the first page, by setting `cursorX` properly. However, I am still not able to figure out why the heading on the second page does not center.

**Comment by deepakjois** [comment]
Now that #76 is fixed, I just wanted to bring back focus to this issue. The problem here seems to be that setting the direction in the `newPage` hook is a bit too late for all the X and Y alignments to happen properly. I can’t think of a good way to maintain directionality smoothly when switching from one frame to another.

**Comment by simoncozens** [comment]
OK, things have now changed (see #83) and the document has a base direction set in `<document class>.pageTemplate.direction`. So although this patch will need to be redone it should be very easy now. I'll discuss the other points in #83.

**Pull request closed without merging**
