### PR TITLE
Add development history visualization post and cleanup GH-Pages code

### PR DESCRIPTION
**Pull request by alerque**
This fixes a few odds and ends on the Github Pages site and adds a new post with a visualization I was playing with and thought others might want to see too. The video itself is stored in LFS so it shouldn't hurt the size of the repo and could potentially be updated from time to time.

### CODE REVIEW

**Comment by alerque** [comment]
Ug. It doesn't look like GH Pages supports the Jekyll plugin system. Let me look into that.

**Comment by alerque** [comment]
Humbug. I guess Github doesn't want people being able to run arbitrary Ruby code on their servers. Because sand-boxing is hard. Oh well.

**Comment by simoncozens** [comment]
Is it worth splitting this up into doable chunks?

**Comment by alerque** [comment]
Yes probably. I should make the temp dir stuff less specific to my dev machine too.

**Comment by alerque** [comment]
Wait, my last comment was on the wrong PR. What do you mean my "doable chunks"? I can rebase to factor out the attempt at using a Jekyll plugin if that's what you mean. It works on local Jekyll instances but not on GHP. If that's not what you mean then I'm confused.

**Comment by alerque** [comment]
I found another issue with the code (accidentally deleted line of markup) so I went ahead and rebased this and stripped the plugin attempt while I was in there.

**Comment by alerque** [comment]
Better hold off merging this for a sec, I setup GH-Pages to test build from my fork and it looks like LFS isn't serving up  the video  file as expected. Standby for tweaks.

**Comment by alerque** [comment]
There this link arrangement should work both for local Jekyll for testing, on anybody's fork (e.g. [mine](https://alerque.github.io/sile/)) on Github¹, and of course from the master GH Pages site.

<sub>¹ After you merge this—the video tag reference to the media file will not work from forks until the LFS stuff is in your repo.</sub>

**Comment by simoncozens** [comment]
Should I expect this:


> The page build completed successfully, but returned the following warning:
> 
> You are attempting to use the 'pygments' highlighter, which is currently unsupported on GitHub Pages. Your site will use 'rouge' for highlighting instead. To suppress this warning, change the 'highlighter' value to 'rouge' in your '_config.yml'. For more information, see https://help.github.com/articles/page-build-failed-config-file-error/#fixing-highlighting-errors.

**Comment by alerque** [comment]
@simoncozens We aren't actually using the syntax highlighter at all yet, but we probably _will_ so we might as well specify one Github allows.

**Pull request merged**
