### PR TITLE
Using crop marks cause %ph and %pw units to compute bad measures, fix…

### PR DESCRIPTION
**Pull request by gnodet**
…es #337

Also enhance the cropmarks package so that the header can be overridden (useful for testing as it includes the date/hour by default)

### CODE REVIEW

**Comment by gnodet** [comment]
Is there any known differences between lua 5.2 and 5.3 to cause such a test to fail ?

**Comment by simoncozens** [comment]
Looks like the "draw line" debug code needs to be fixed to deal with the integer/float change in Lua 5.3.

**Comment by simoncozens** [comment]
Very nice, thank you!

**Comment by alerque** [comment]
Good catch @gnodet!

**Pull request merged**
