### PR TITLE
Add support for CMYK and grayscale colors.

### PR DESCRIPTION
**Pull request by lprndn**
Hi!
As said in #444, I tried to implement cmyk and grayscale colors in SILE.
Everything seems to work as you can see in this quick example: [colors.pdf](https://github.com/simoncozens/sile/files/785048/colors.pdf).
Might not be the best implementation as I'm a newbie in lua  but it doesn't break anything either, which is nice, I think.
So now, you can set colors as you used to but you can also specify each channel's value separated by a space (between 0 and 255, decimals separated by a comma `125.65`).

`colorparser` will then choose which type of color it is depending of the number of channels: 
`\color[color = 125]{1 for grayscale}`
`\color[color=0 0 255]{3 for rgb}`
`\color[color=255 255 0 0]{4 for cmyk}`

Should help a lot to use cmyk colors when printing pdfs even if ICC profiles are still needed for consistent colors.

Have a nice day.

### CODE REVIEW

**Comment by alerque** [comment]
This looks like a great feature add. I'll leave it for @simoncozens to decide if this is how he wants to implement it, but I took the liberty of cleaning up the lua coding style just a touch and normalizing the way patterns are matched against the way SILE was already doing it. This shouldn't be functionally any different.

**Comment by lprndn** [comment]
Thanks! I'll try to be tidier next time!

**Comment by simoncozens** [comment]
Lovely, thank you very much!

**Comment by alerque** [comment]
I just realized one thing missing from this PR was documentation ;-) We should probably make a note about this in the manual.

**Pull request merged**
