### PR TITLE
Set default papersize to A4

### PR DESCRIPTION
**Pull request by alerque**
See issue #144 for _why_ I started on this.

As for implementation, so far this only does the final fallback step.

I tried setting something like `plain:declareOption("papersize", "a4")` in the plain class file but got unexpected results. I'm not sure yet how to code that part.

 - [x] ~~Set sensible defaults in document classes~~
 - [x] Set sensible default fallback for any clases that don't specify
 - [x] Update documentation

### CODE REVIEW

**Comment by alerque** [comment]
The remaining todo items on this have been finished and I rebased it on master. Commit e97b2f8 actually removes a default rather than adds one as in my first todo item, but I couldn't convince myself that any of the default classes needs an override for this. The nearest miss is the "book" class which could conceivably default to quarto or some other common book size, but I rather think that keeping the A4 default across the classes will make it easier for people to understand what _is_ changing (e.g. the page layout changes) without also changing other parameters to arbitrary values that are likely not the final values anyway.

**Comment by alerque** [comment]
Any feedback on this one?

**Comment by alerque** [comment]
Rebased to apply cleanly on master.

**Comment by simoncozens** [comment]
Thanks very much for this - lots of hard work!

**Pull request merged**
