### PR TITLE
Drop libthai dependency

### LINKED ISSUE #429: justenoughthai.c:43:3: error: unknown type name ‘ThBrk’
I just jumped on a system I don't usually use for this and tried to compile SILE. After configure, make dies with an error. The relevant bit seems to be:

```
Making all in libtexpdf
make[1]: Entering directory '/home/caleb/projects/sile/libtexpdf'
make  all-am
make[2]: Entering directory '/home/caleb/projects/sile/libtexpdf'
make[2]: Leaving directory '/home/caleb/projects/sile/libtexpdf'
make[1]: Leaving directory '/home/caleb/projects/sile/libtexpdf'
Making all in src
make[1]: Entering directory '/home/caleb/projects/sile/src'
  CC       justenoughthai_la-justenoughthai.lo
justenoughthai.c: In function ‘thai_breakpoints’:
justenoughthai.c:43:3: error: unknown type name ‘ThBrk’
   ThBrk* brk = th_brk_new(NULL);
   ^~~~~
justenoughthai.c:43:16: warning: implicit declaration of function ‘th_brk_new’ [-Wimplicit-function-declaration]
   ThBrk* brk = th_brk_new(NULL);
                ^~~~~~~~~~
justenoughthai.c:43:16: warning: initialization makes pointer from integer without a cast [-Wint-conversion]
justenoughthai.c:44:15: warning: implicit declaration of function ‘th_brk_find_breaks’ [-Wimplicit-function-declaration]
   int n_pos = th_brk_find_breaks(brk, buffer, pos, l);
               ^~~~~~~~~~~~~~~~~~
justenoughthai.c:55:3: warning: implicit declaration of function ‘th_brk_delete’ [-Wimplicit-function-declaration]
   th_brk_delete(brk);
   ^~~~~~~~~~~~~
make[1]: *** [Makefile:674: justenoughthai_la-justenoughthai.lo] Error 1
make[1]: Leaving directory '/home/caleb/projects/sile/src'
make: *** [Makefile:510: all-recursive] Error 1
```

It there some version requirement of a dependency that isn't getting caught by configure?

### PR DESCRIPTION
**Pull request by khaledhosny**
Not needed since ICU is a hard dependency now and should provide Thai
line breaking support. I casually checked the Thai example but since I
don’t know ant Thai I can’t really verify the correctness of the output.

Fixes #429.

### CODE REVIEW

**Comment by simoncozens** [comment]
I like the idea, but I'd like to do a bit of research first - can we find examples where `libthai` and ICU give different breakpoints, and if so, what do Thai readers think about them?

**Comment by khaledhosny** [comment]
I don’t know, but ICU is used in LibreOffice so I assume it is good. I don’t know if @mhosken has any insights here.

**Comment by alerque** [comment]
@pepa65 also seems to be a Thai speaker if there are any actual breaking differences to review.

**Comment by pepa65** [comment]
I've tried to look into this, but couldn't find anything about libthai and ICU differences in word breaking. I know that libthai works with a dictionary that can be modified (updates happen regularly). I would be very interested to review any differences. Things I read in the past was that ICU was outdated (quicker?) so I wasn't immediately happy with the proposal to remove libthai, although I would cheer for fewer dependencies.

**Comment by mhosken** [comment]
ICU linebreaking for Thai is OKish. I would love to bring it in line with the Khmer one. But that would involve a bunch of local technical politics I can't address until the end of this year. There's nothing wrong with the libthai one, but equally there is no real harm switching to ICU either. It's up to you really.

**Comment by simoncozens** [comment]
Let's do it, then. Less code is better than more code.

**Pull request merged**
